services:
  mongodb:
    image: 'mongo:latest'
    networks:
      - mynetwork
  budget-king:
    image: "budget-king:0.4.9"
    ports:
      - "8080:8080"
    networks:
      - mynetwork
    environment:
      - MONGO_URI=mongodb://mongodb:27017/mydatabase?authSource=admin

networks:
  mynetwork:
    driver: bridge

